name: "Build"
on: [push]

jobs:
  build-papyrus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v2
        with:
          name: papyrus
          path: target/release/papyrus
  build-jenkins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      - run: ./gradlew jpi --stacktrace
        working-directory: ./plugins/jenkins
      - uses: actions/upload-artifact@v2
        with:
          name: papyrus
          path: plugins/jenkins/build/libs/papyrus-jenkins.hpi
